
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnv } from '../../lib/env.ts';

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL') ?? '';
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_ANON_KEY') ?? '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
